version: "3"
services:

  database:
    image: mysql:8.0
    environment:
      - 'MYSQL_ROOT_PASSWORD=1234'
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8080:8080

  employees:
    image: application_employee
    ports:
      - 5000:5000
    environment:
      - PRODUCTION="PRODUCTION"
